packages/cohort/src/pages/CohortMemberList.js, packages/common-lib/src/services/attendanceRegistryService.js, packages/profile/src/components/SelfAttendanceSheet.js
Changes & fixes in student mark attendance workflow
Check the mark attendance workflow for student & add the required data for API calling (Partially)
remove(comment) the all other provision(if any) except the mark attendance against the student list.
=> Task #213870 Fix: Changes & fixes in student mark attendance workflow

packages/cohort/src/pages/CohortDetails.js, packages/profile/src/components/Camera.js, packages/profile/src/components/SelfAttendanceSheet.js
**Description**
Add config (column) on cohort level, to show the camera while marking the attendance
**Acceptance Criteria**
I should be able to submit the attendance with or without taking pic as per the config
**Steps for Implementation**
- Add a column attendanceCaptureImage in cohorts table against the cohort
- If set to yes, in frontend the user should see the camera while taking the attendance
- If set to no, attendance should be submitted without taking the photo.
=> Issue #213840 feat: Add config on cohort level to show/not to show the camera while marking the attendance

packages/cohort/src/pages/CohortDetails.js, packages/common-lib/src/components/Widget.js
**Description**
Teacher should be able to mark his/her attendance specific to cohort (school/class).
**Acceptance Criteria**
- Teacher should be able to mark his/her attendance specific to cohort (school/class)
**Steps for Implementation**
- Show the modal popup to mark(Present / absent) the attendance while clicking on "Mark My Attendance" widget when teacher goes inside the specific cohort (school/class) & remove the current route which are written on "Mark My Attendance" widget.
- After marking the attendance, teacher will be able to change their previous attendance type.
=> Isssue #214005 feat: Teacher Attendance Specific to Cohort

packages/cohort/src/pages/CohortList.js, packages/cohort/src/pages/CohortMemberList.js, packages/common-lib/src/services/cohortRegistryService.js
**Description**
Show the cohort list on the basis of cohort members having role teacher for logged in user
**Acceptance Criteria**
Logged in user(teacher) should be able to see the cohort list on the basis of cohort members having role teacher for logged in user
**Steps for Implementation**
- Write a new function which will call a new API which get the cohortIds from the cohort member list table where the role should be teacher & user will be the logged in user.
- Pass these cohort ids to existing cohort search API in a filter params.
=> Issue #214069 feat: Show the cohort list on the basis of cohort members having role teacher for logged in user

packages/cohort/src/pages/CohortMemberList.js, packages/common-lib/src/services/attendanceRegistryService.js, packages/profile/src/components/SelfAttendanceSheet.js
API integration of AttendanceSearch api call and update status on user list .
1. user will able to see status of attendance beside of take attendance.
1. Integrate api of attendance search
2. use status of attendance on user list
=> Task #213997: API integration of AttendanceSearch api call and update status on user list.

.well-known/assetlinks.json
=> Issue #000 chore: adding assets-links.json file

packages/cohort/src/pages/CohortDetails.js, packages/cohort/src/pages/CohortMemberList.js, packages/teacher-app/src/pages/Generic.js, packages/teacher-app/src/pages/MyClasses.js, packages/teacher-app/src/pages/TeacherHome.js
1. Fix the profile alphabet representation to follow the order of the user's first name and last name.
2. The student list should be impartial. It appears that the application has segregated colours based on gender, which seems inappropriate.
3. Show the full name of the class when clicking on the class list.
4. Remove the admin screen since it's unnecessary; keep it exclusive to the teacher's screen.
5. Keep the default picture as a neutral profile icon instead of assigning any specific picture.
=> Issue #000 UI fixes

packages/cohort/src/pages/CohortDetails.js, packages/common-lib/src/components/layout/AppBar.js
- Comment the code for language switch
- Fixed issue about text indentation
=> Issue #000 fix: ui issues

packages/cohort/src/pages/CohortMemberList.js
=> issue #000 fix: marking individual attendance

src/pages/index.tsx
=> Issue #0000 chore: Removed console.log

package-lock.json, package.json, src/pages/index.tsx, src/styles/customStyles.tsx
=> Issue #0000 chore: Imported login page dynamically

package.json, src/components/WeekCalender.tsx, src/pages/Dashboard.tsx, src/services/AttendanceService.ts, src/styles/globals.css, src/utils/Helper.ts, src/utils/Interfaces.ts
=> Issue #PS-321 feat:Date wise attendance status card in calendar

src/pages/Dashboard.tsx
=> Issue #PS-320 undefined issue fixed

src/pages/Dashboard.tsx
[fixed: Dashboard page changes for list api & close popup
=> Dashboard page changes for list api & close popup

packages/cohort/src/components/Dialog/DialogMsg.js, packages/cohort/src/pages/CohortMemberList.js
FE- Enhance Visibility of Marked Student Attendance Status
=> Issue #219470 chore: FE- Show confirmation message when bulk attendance is marked

src/pages/attendance-overview.tsx
=> #PS-396 fix: Fix autoselect on dropdown for date range select

src/components/AttendanceStatusListView.tsx, src/components/DateRangePopup.tsx, src/pages/attendance-overview.tsx, src/pages/learner-profile.tsx, src/pages/learner-profile/[userId].tsx
=> Issue #PS-274 fix: UI bug fixes

src/components/Header.tsx, src/pages/attendance-overview.tsx
=> Issue #PS-396 chore: Modified sorting code to handled undefined case and fixed header at top

src/pages/attendance-history.tsx, src/pages/dashboard.tsx
=> Issue #PS-286 fix: Fixed limit as 0 for cohort member search api calls

src/pages/learner-profile/[userId].tsx
=> Issue #PS-314 feat: language constant update in Learner View profile

src/components/AttendanceStatus.tsx, src/pages/dashboard.tsx
=> Issue #PS-286 fix: fixed UI issue on attendance status banner on dashboard

src/components/Header.tsx, src/components/MenuDrawer.tsx, src/pages/dashboard.tsx, src/styles/globals.css
=> Issue PS-652 fix:scrolling issue when user uses the scroll up/down button

src/services/Interceptor.ts
=> Issue #PS-320 chore: token restored as per changed API response.

src/components/AttendanceStatus.tsx, src/components/MarkBulkAttendance.tsx, src/components/MonthCalender.tsx, src/hooks/useDeterminePathColor.js, src/pages/learner-attendance-history.tsx, src/utils/Interfaces.ts
=> Issue #PS-294 chore: Build issues fixed

src/pages/attendance-overview.tsx
=> Issue #PS-627 chore: Removed Seach and sort functionality for all centers selection

public/locales/en/common.json, public/locales/hi/common.json, public/locales/mr/common.json, src/components/DateRangePopup.tsx, src/components/Modal.tsx, src/pages/attendance-overview.tsx
=> Issue #PS-388 chore: Added feature to show number of days attendance marked out of 7 days on attendance overview page

public/locales/en/common.json, public/locales/hi/common.json, public/locales/mr/common.json, src/components/LearnerModal.tsx, src/components/StudentStatsCard.tsx, src/pages/learner/[userId].tsx, src/pages/profile.tsx, src/utils/Interfaces.ts
Issue #PS-312 feat:Teacher Profile update ui fixes, add dyanamic traslation of fields  by name to label
=> Issue #PS-312 feat:Teacher Profile update ui fixes, add dyanamic traslation of fields  by name to label

src/components/DateRangePopup.tsx, src/components/UpDownButton.tsx, src/pages/attendance-overview.tsx, src/pages/dashboard.tsx, src/pages/profile.tsx, src/styles/globals.css
=> Issue #PS-657 fix:Tracker Bug fixes

src/pages/login.tsx
=> Issue #220010 bug: language flickering issue solved

src/components/MonthCalender.tsx, src/pages/dashboard.tsx
=> Issue #0000 bug: month not changing in attendance history - issue fixed

src/pages/dashboard.tsx, src/pages/login.tsx
=> Issue #0000 bug: dropdown initial cohort value not coming issue fixed

src/pages/profile.tsx
=> Issue #PS-000 chore; Fixed build Issue

src/components/WeekCalender.tsx, src/styles/globals.css
=> Issue #0000 bug: border added to current date

src/pages/dashboard.tsx
=> Issue #0000 bug: api call shifted on button click

src/components/MonthCalender.tsx, src/styles/customStyles.tsx, src/styles/globals.css
=> Issue #0000 feat: color added to selected date range

src/components/MonthCalender.tsx
=> Issue #000 chore: fixed build issue

src/components/AttendanceStatus.tsx, src/components/CohortAttendanceListView.tsx, src/components/DateRangePopup.tsx, src/components/LearnerAttendanceStatsListView.tsx, src/hooks/useAttendanceRangeColor.js
=> Issue #PS-384 chore: Fixed zero attendance color Issue

src/pages/_app.tsx, src/pages/login.tsx
Issue #PS-807 feat: Integrate Telemetry on to Login and attendance pages
=> Issue #PS-807 feat: Integrate Telemetry on to Login and attendance pages

src/pages/attendance-history.tsx, src/pages/attendance-overview.tsx, src/pages/dashboard.tsx, src/pages/learner-attendance-history.tsx, src/pages/learner/[userId].tsx, src/pages/profile.tsx
=> Issue #PS-000 chore: Modified toast messages for something went wrong

src/pages/_app.tsx, src/utils/telemetry.js
=> Issue #PS-390 fix: Hide telemetry calls

src/components/MarkBulkAttendance.tsx
=> Issue #PS-390 fix: FIxed response

packages/cohort/src/pages/CohortDetails.js, packages/cohort/src/pages/CohortList.js, packages/cohort/src/pages/CohortMemberList.js
=> Issue #000 fix: Do not explicitly show Parent cohort name

src/utils/telemetry.js
[FRONTEND] Integrate telemetry into the teacher application
=> Issue #PS-704 feat: [FRONTEND] Integrate telemetry into the teacher application

src/components/DropOutModal.tsx, src/pages/dashboard.tsx, src/styles/globals.css
=> Issue #PS-798 fix: UI Reusable components

src/components/CohortLearnerList.tsx
=> Resolved issue

src/components/MonthCalender.tsx, src/utils/Interfaces.ts
=> Issue #PS-000 chore: Resolved build Issue

src/components/Header.tsx
=> Issue #000 chore: build issue resolved

public/locales/en/common.json
=> Issue #0000 chore: English langauge constants issue fixed

src/components/LearnerAttendanceStatsListView.tsx
=> Issue #PS-0000 Attendance overview list layout fix

package-lock.json, package.json
=> Issue #PS-1247 chore : MUI 5 installed
